### ISSUE TITLE
data.json traviscibot deployments failing after 22 Oct

### ISSUE THREAD

**Issue by anssiko** [foolip/day-to-day#2]
This most awesome [spec and test activity tracker](https://foolip.github.io/day-to-day/) stopped doing daily deployments of [`data.js`](https://github.com/foolip/day-to-day/blob/gh-pages/data.json) after 22 Oct.

I reviewed [commits](https://github.com/foolip/day-to-day/commits/master) that landed on 22 Oct and was unable to find an obvious reason why traviscibot deployments started failing after that date.

**Comment by foolip** [comment]
The setup is pretty fragile and does break in particular when there are colliding IDs due to new specs being added to specref. But this seems like it was caused by me migrating to travis-ci.com, the daily cron job doesn't seem to have been running recently.

**Comment by foolip** [comment]
The reason was explained in a support email about migrating the web-platform-tests org: "There's however one limitation on setting cron jobs that might affect your team here: Cron jobs can only be configured for branches that have already been built on travis-ci.com, and since the build history is kept but will not be migrated right away, you might not be able to setup cron jobs unless you trigger a build on that branch first."

So I'll push some stuff to master until it works again.

**Comment by anssiko** [comment]
Thanks for the explanation! The tool is already making great job parsing the inconsistent specref data.

**Comment by foolip** [comment]
I had to make a small fix, and now it's updated again! Thanks for reporting, Anssi!
